In [2]:
import numpy as np

In [23]:
def calculate_kernel(x, y, kernel, kernel_param):
    """
    Calculate the kernel between x and y
    """
    if kernel == 'linear':
        return np.dot(x, y)
    elif kernel == 'poly':
        return (1 + np.dot(x, y)) ** kernel_param
    elif kernel == 'rbf':
        return np.exp(-kernel_param * np.linalg.norm(x - y) ** 2)

def calculate_kernel_matrix(X, kernel, kernel_param):
    """
    Calculate the kernel matrix for the data X
    """
    K = np.zeros((X.shape[0], X.shape[0]))
    for i in range(len(X)):
        for j in range(len(X)):
            print(X_train[i])
            print(X_train[j])
            print(np.dot(X_train[i], X_train[j]))
            K[i, j] = calculate_kernel(X[i], X[j], kernel, kernel_param)
    
    return K

X_train = np.array([[1, 2], [2, 3], [3, 4]])

kernel_X = calculate_kernel_matrix(X_train, 'poly', 0.0001)

print(kernel_X)

print(np.exp(5645.53423423))

[1 2]
[1 2]
5
[1 2]
[2 3]
8
[1 2]
[3 4]
11
[2 3]
[1 2]
8
[2 3]
[2 3]
13
[2 3]
[3 4]
18
[3 4]
[1 2]
11
[3 4]
[2 3]
18
[3 4]
[3 4]
25
[[1.00001792 1.00002197 1.00002485]
 [1.00002197 1.00002639 1.00002944]
 [1.00002485 1.00002944 1.00003258]]
inf


C:\Users\bersi\AppData\Local\Temp\ipykernel_11132\2713488236.py:32: RuntimeWarning: overflow encountered in exp
  print(np.exp(5645.53423423))


In [20]:
np.exp(5874.674294394035)
np.sign(0)

C:\Users\bersi\AppData\Local\Temp\ipykernel_11132\422941819.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(5874.674294394035)


1.0

In [3]:
for a in ['A', 'B', 'C', 'D']:
    data = np.load("../Data/dataset_{}.npz".format(a))
    print(data.files)
    print(data['arr_0'].shape)
    print(data['arr_1'].shape)
    print(data['arr_2'].shape)
    print(data['arr_3'].shape)

['arr_0', 'arr_1', 'arr_2', 'arr_3']
(1500, 2)
(1500,)
(500, 2)
(500,)
['arr_0', 'arr_1', 'arr_2', 'arr_3']
(1500, 2)
(1500,)
(500, 2)
(500,)
['arr_0', 'arr_1', 'arr_2', 'arr_3']
(1500, 64)
(1500,)
(297, 64)
(297,)
['arr_0', 'arr_1', 'arr_2', 'arr_3']
(400, 30)
(400,)
(169, 30)
(169,)
