In [2]:
import numpy as np

In [3]:
def calculate_kernel(x, y, kernel, kernel_param):
    """
    Calculate the kernel between x and y
    """
    if kernel == 'linear':
        return np.dot(x, y)
    elif kernel == 'poly':
        return (1 + np.dot(x, y)) ** kernel_param
    elif kernel == 'rbf':
        return np.exp(-kernel_param * np.dot(x - y, x - y))

def calculate_kernel_matrix_old(X, kernel, kernel_param):
    """
    Calculate the kernel matrix for the data X
    """
    K = np.zeros((X.shape[0], X.shape[0]))
    for i in range(len(X)):
        for j in range(len(X)):
            K[i, j] = calculate_kernel(X[i], X[j], kernel, kernel_param)
    return K

def calculate_kernel_matrix(X, kernel, kernel_param):
    """
    Calculate the kernel matrix for the data X
    """
    if(kernel == 'linear'):
        return np.matmul(X, X.T)
    elif(kernel == 'poly'):
        return (1 + np.matmul(X, X.T)) ** kernel_param
    elif(kernel == 'rbf'):
        # kernel(X, Y) = exp(-gamma * ||X - Y||^2)
        return (np.exp(-kernel_param * (np.sum(X**2, axis=1)[:, np.newaxis] + np.sum(X**2, axis=1) - 2 * np.matmul(X, X.T))))

X_train = np.array([[1, 2], [2, 3], [3, 4]])

kernel_X = calculate_kernel_matrix_old(X_train, 'rbf', 4)
time_taken = %timeit -o calculate_kernel_matrix_old(X_train, 'poly', 4)
print(kernel_X)
kernel_X = calculate_kernel_matrix(X_train, 'rbf', 4)
time_taken = %timeit -o calculate_kernel_matrix(X_train, 'poly', 4)
print(kernel_X)

12.3 µs ± 170 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
[[1.00000000e+00 3.35462628e-04 1.26641655e-14]
 [3.35462628e-04 1.00000000e+00 3.35462628e-04]
 [1.26641655e-14 3.35462628e-04 1.00000000e+00]]
2.33 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
[[1.00000000e+00 3.35462628e-04 1.26641655e-14]
 [3.35462628e-04 1.00000000e+00 3.35462628e-04]
 [1.26641655e-14 3.35462628e-04 1.00000000e+00]]


In [20]:
np.exp(5874.674294394035)
np.sign(0)

C:\Users\bersi\AppData\Local\Temp\ipykernel_11132\422941819.py:1: RuntimeWarning: overflow encountered in exp
  np.exp(5874.674294394035)


1.0

In [3]:
for a in ['A', 'B', 'C', 'D']:
    data = np.load("../Data/dataset_{}.npz".format(a))
    print(data.files)
    print(data['arr_0'].shape)
    print(data['arr_1'].shape)
    print(data['arr_2'].shape)
    print(data['arr_3'].shape)

['arr_0', 'arr_1', 'arr_2', 'arr_3']
(1500, 2)
(1500,)
(500, 2)
(500,)
['arr_0', 'arr_1', 'arr_2', 'arr_3']
(1500, 2)
(1500,)
(500, 2)
(500,)
['arr_0', 'arr_1', 'arr_2', 'arr_3']
(1500, 64)
(1500,)
(297, 64)
(297,)
['arr_0', 'arr_1', 'arr_2', 'arr_3']
(400, 30)
(400,)
(169, 30)
(169,)
